<?php

namespace BM\WarhammerBundle\Repository;

/**
 * FigurineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurineRepository extends \Doctrine\ORM\EntityRepository
{
}
