<?php

namespace BM\WarhammerBundle\Repository;

/**
 * GearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GearRepository extends \Doctrine\ORM\EntityRepository
{
}
