TP\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: TP\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
